### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by coderobe** [syscl/EnableLidWake#2]
This is a fork of https://github.com/coderobe/AzulPatcher4600, and you happily relicensed it under the `Creative Commons Attribution-NonCommercial 4.0 Unported License` (https://github.com/syscl/EnableLidWake/blob/master/EanbleLidWake/EnableLidWake.cpp#L6)

If anything, i'd like you to add me and my copyright in the comment blocks above the code (e.g. https://github.com/syscl/EnableLidWake/blob/master/EanbleLidWake/EnableLidWake.cpp#L2)  

Like `Copyright © 2017 coderobe`.  
(see https://github.com/coderobe/AzulPatcher4600/blob/master/genericPatcher/kern_patchset.cpp#L4)  

To imply you superseding me as author, you should put my © above yours, for chronological authorship changes.  

Even though you're technically violating my project's license, i'm not gonna make a huge fuss about it - but i'd like you to ref. me as original author / previous author.  

Thanks.

**Comment by camielverdult** [comment]
thumbs up

**Comment by coderobe** [comment]
Would you please take a look at this issue?

**Comment by syscl** [comment]
Excuse me, I still don't quiet understand why you think they are the same patch? Enable Lid Wake is a patch that I discovered in about 2015 by myself if you look into RehabMan's Repo. They are totally different patch on framebuffer for totally different function.  

And if my license is incorrect, I will correct it(thank you for your kind remind), but the patch is totally different from simply framebuffer patch.

syscl

**Comment by coderobe** [comment]
I understand that the patches are different, but your codebase is based on a fork of my code and thus should inherit the copyright header and license

**Comment by coderobe** [comment]
This has still not been addressed.

**Comment by syscl** [comment]
@coderobe tl;dr

It's been a while since my life went through really tough such that I did not have time on GitHub (you can see my recent commits). As for you pointing out, I added credit for your code base in my code (please give it a look) and give me some help if this indeed solve the issue.

Thank you,
syscl

**Comment by coderobe** [comment]
typo'd my name in https://github.com/syscl/EnableLidWake/blob/ebf493a87220e11180d6bcad0606c34f597296a0/EanbleLidWake/kern_start.cpp#L6 and it's not just 'credit', it's copyright. Just like your own one above. Same goes for https://github.com/syscl/EnableLidWake/blob/ebf493a87220e11180d6bcad0606c34f597296a0/README.md

**Comment by syscl** [comment]
@coderobe Please see new commit and see if this works.

syscl

**Comment by coderobe** [comment]
The name is still wrong, it's `coderobe`, not `corerobe`
See https://github.com/syscl/EnableLidWake/blob/067187a650815911ad039993aa3e6a533d6da5ab/README.md, https://github.com/syscl/EnableLidWake/blob/d5c339add9e491836ab590dcd9d2a22d126aa63c/EnableLidWake/EnableLidWake.hpp#L2, https://github.com/syscl/EnableLidWake/blob/d5c339add9e491836ab590dcd9d2a22d126aa63c/EnableLidWake/EnableLidWake.cpp#L2

**Comment by syscl** [comment]
@coderobe Check the latest commits.

**Comment by coderobe** [comment]
:+1:
