### ISSUE TITLE
能否解决Iris plus 640睡眠唤醒有时候黑屏？

### ISSUE THREAD

**Issue by hoanX** [syscl/EnableLidWake#3]
hi syscl：

1. 我看过你发过解决iris 540唤醒黑屏的补丁
2. 将0A  -->  0F,我也制作类似的补丁，可以解决有时候唤醒黑屏问题，但是出现了使用过程出现花屏（尝试过修复edid，也没有效果），添加你的EnableLidWake也没有缓解

AppleIntelKBLGraphicsFramebuffer
find：0A0BE300 00070600 03000000 04000000
replace：0F0BE300 00070600 03000000 04000000

3. 再10.14上的AppleIntelKBLGraphicsFramebuffer出现了变化和之前的完全不一样了，也没法使用补丁了

**Comment by syscl** [comment]
Hi @hoanX 十分感谢你的反馈，能否提供你显卡的信息？以及注入的IG-Platform-ID？

我会考虑添加KBL的支持谢谢！

**Comment by syscl** [comment]
你好，我已经添加kabylake的支持，请尝试最新的[EnableLidWake.kext.zip](https://github.com/syscl/EnableLidWake/files/2334046/EnableLidWake.kext.zip). 因为我没有KBL的Windows笔记本，所以麻烦上传[maclog](https://github.com/syscl/maclog)所给出的日志以确定ELW是否顺利修复了睡眠黑屏问题.

谢谢

**Comment by hoanX** [comment]
@syscl 非常感谢你能及时处理这个问题

我尝试了你的最新版本，但是还没能解决问题，多次睡眠还是有几率出现黑屏

我的设备信息：
xps 9360  3k分辨率
cpu：i7-7560u,iris plus 640,IG-Platform-ID:0x59260002

smbios使用的是mbp14,1，安装系统版本10.13.6
附件是maclog拿到的日志，如果还需要其他信息请告诉我
[system.log](https://github.com/syscl/EnableLidWake/files/2334370/system.log)

**Comment by syscl** [comment]
谢谢你的log，从日志上看ELW并没有找到相应的破解位置，我会继续完善。

谢谢

**Comment by hoanX** [comment]
感谢，如果有什么进展，我随时都可以帮忙测试

**Comment by hoanX** [comment]
我已经解决这个问题了，仿冒iris 540,其中IG-Platform-ID：0x19260000最适合，使用一周以来没出现过什么问题，其他的id都有些问题
